### ISSUE TITLE
We can not scrap https://torrentgee16.com, something wrong.

### ISSUE THREAD

**Issue by rudyannnn** [geekdifferent/torrent_web_scraper#1]
We can not scrap https://torrentgee16.com, something wrong.

**Comment by geekdifferent** [comment]
New repo was created. This repo is not going to be updated.

GitHub Repo : https://github.com/devinlife/torrent_web_scraper
Project 소개 : https://devinlife.com/project%20torrnet_web_scraper/torrent-web-scraper
